// Date: 7/28/2014 1:48:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.naviaux.eam.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelExtractor extends ModelBase {
	//fields
	ModelRenderer Base;
	ModelRenderer LowerBase1;
	ModelRenderer LowerBase2;
	ModelRenderer LowerBase3;
	ModelRenderer LowerBase4;
	ModelRenderer UpperBase1;
	ModelRenderer UpperBase2;
	ModelRenderer UpperBase3;
	ModelRenderer UpperBase4;

	public ModelExtractor () {
		textureWidth = 64;
		textureHeight = 64;

		Base = new ModelRenderer(this, 0, 38);
		Base.addBox(0F, 0F, 0F, 16, 9, 16);
		Base.setRotationPoint(-8F, 15F, -8F);
		Base.setTextureSize(64, 64);
		Base.mirror = true;
		setRotation(Base, 0F, 0F, 0F);
		LowerBase1 = new ModelRenderer(this, 0, 19);
		LowerBase1.addBox(0F, 0F, 0F, 16, 1, 5);
		LowerBase1.setRotationPoint(-8F, 14F, 3F);
		LowerBase1.setTextureSize(64, 64);
		LowerBase1.mirror = true;
		setRotation(LowerBase1, 0F, 0F, 0F);
		LowerBase2 = new ModelRenderer(this, 0, 25);
		LowerBase2.addBox(0F, 0F, 0F, 16, 1, 5);
		LowerBase2.setRotationPoint(-8F, 14F, -8F);
		LowerBase2.setTextureSize(64, 64);
		LowerBase2.mirror = true;
		setRotation(LowerBase2, 0F, 0F, 0F);
		LowerBase3 = new ModelRenderer(this, 0, 31);
		LowerBase3.addBox(0F, 0F, 0F, 5, 1, 6);
		LowerBase3.setRotationPoint(-8F, 14F, -3F);
		LowerBase3.setTextureSize(64, 64);
		LowerBase3.mirror = true;
		setRotation(LowerBase3, 0F, 0F, 0F);
		LowerBase4 = new ModelRenderer(this, 22, 31);
		LowerBase4.addBox(0F, 0F, 0F, 5, 1, 6);
		LowerBase4.setRotationPoint(3F, 14F, -3F);
		LowerBase4.setTextureSize(64, 64);
		LowerBase4.mirror = true;
		setRotation(LowerBase4, 0F, 0F, 0F);
		UpperBase1 = new ModelRenderer(this, 0, 0);
		UpperBase1.addBox(0F, 0F, 0F, 16, 1, 4);
		UpperBase1.setRotationPoint(-8F, 13F, 4F);
		UpperBase1.setTextureSize(64, 64);
		UpperBase1.mirror = true;
		setRotation(UpperBase1, 0F, 0F, 0F);
		UpperBase2 = new ModelRenderer(this, 0, 5);
		UpperBase2.addBox(0F, 0F, 0F, 16, 1, 4);
		UpperBase2.setRotationPoint(-8F, 13F, -8F);
		UpperBase2.setTextureSize(64, 64);
		UpperBase2.mirror = true;
		setRotation(UpperBase2, 0F, 0F, 0F);
		UpperBase3 = new ModelRenderer(this, 0, 10);
		UpperBase3.addBox(0F, 0F, 0F, 4, 1, 8);
		UpperBase3.setRotationPoint(-8F, 13F, -4F);
		UpperBase3.setTextureSize(64, 64);
		UpperBase3.mirror = true;
		setRotation(UpperBase3, 0F, 0F, 0F);
		UpperBase4 = new ModelRenderer(this, 24, 10);
		UpperBase4.addBox(0F, 0F, 0F, 4, 1, 8);
		UpperBase4.setRotationPoint(4F, 13F, -4F);
		UpperBase4.setTextureSize(64, 64);
		UpperBase4.mirror = true;
		setRotation(UpperBase4, 0F, 0F, 0F);
	}

	public void render (Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Base.render(f5);
		LowerBase1.render(f5);
		LowerBase2.render(f5);
		LowerBase3.render(f5);
		LowerBase4.render(f5);
		UpperBase1.render(f5);
		UpperBase2.render(f5);
		UpperBase3.render(f5);
		UpperBase4.render(f5);
	}

	private void setRotation (ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles (float f, float f1, float f2, float f3, float f4, float f5, Entity entitiy) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entitiy);
	}

}
