// Date: 7/28/2014 5:33:25 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.naviaux.eam.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSmelter extends ModelBase {
	//fields
	ModelRenderer Base;
	ModelRenderer Shaft;
	ModelRenderer Node;

	public ModelSmelter () {
		textureWidth = 64;
		textureHeight = 32;

		Base = new ModelRenderer(this, 16, 0);
		Base.addBox(0F, 0F, 0F, 12, 11, 12);
		Base.setRotationPoint(-6F, 13F, -6F);
		Base.setTextureSize(64, 32);
		Base.mirror = true;
		setRotation(Base, 0F, 0F, 0F);
		Shaft = new ModelRenderer(this, 0, 7);
		Shaft.addBox(0F, 0F, 0F, 4, 4, 4);
		Shaft.setRotationPoint(-2F, 9F, -2F);
		Shaft.setTextureSize(64, 32);
		Shaft.mirror = true;
		setRotation(Shaft, 0F, 0F, 0F);
		Node = new ModelRenderer(this, 0, 0);
		Node.addBox(0F, 0F, 0F, 6, 1, 6);
		Node.setRotationPoint(-3F, 8F, -3F);
		Node.setTextureSize(64, 32);
		Node.mirror = true;
		setRotation(Node, 0F, 0F, 0F);
	}

	public void render (Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Base.render(f5);
		Shaft.render(f5);
		Node.render(f5);
	}

	private void setRotation (ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles (float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
